In [87]:
%load_ext autoreload
%autoreload 2

import tensormath as tm
import numba
import numpy as np
from numba import jit

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


Check the conversion subroutines for stress and strain

In [88]:
stress = np.array([ 1000., -200., -200., 1., 2., 3.])

new_stress = tm.convert_stress(stress)
print new_stress

[[  1.00000000e+03   5.00000000e-01   1.00000000e+00]
 [  5.00000000e-01  -2.00000000e+02   1.50000000e+00]
 [  1.00000000e+00   1.50000000e+00  -2.00000000e+02]]


Convert stress forward and back

In [93]:
stress1 = tm.convert_stress(tm.convert_stress(stress))
stress1

array([[ 1000.],
       [ -200.],
       [ -200.],
       [    1.],
       [    2.],
       [    3.]])

In [94]:
strain = [ 1., 2., 3., 4., 5., 6.]

strain1 = tm.convert_strain(strain)
print strain1

strain2 = tm.convert_strain(strain1)
print strain2

[[ 1.   2.   2.5]
 [ 2.   2.   3. ]
 [ 2.5  3.   3. ]]
[[ 1.]
 [ 2.]
 [ 3.]
 [ 4.]
 [ 5.]
 [ 6.]]


Test the rotation subroutines for second order tensors (CTE)

In [95]:
CTE = np.array([ [ 1., 0.1, 0.2], [0.1, 2., 0.3], [0.2, 0.3, 3.]])
A = tm.compute_transformation_matrix(45.)

for i in range(8):
    CTE = tm.rotate_thermal_expansion(A, CTE)
    print CTE

[[ 1.4        -0.5        -0.07071068]
 [-0.5         1.6         0.35355339]
 [-0.07071068  0.35355339  3.        ]]
[[ 2.  -0.1 -0.3]
 [-0.1  1.   0.2]
 [-0.3  0.2  3. ]]
[[ 1.6         0.5        -0.35355339]
 [ 0.5         1.4        -0.07071068]
 [-0.35355339 -0.07071068  3.        ]]
[[ 1.   0.1 -0.2]
 [ 0.1  2.  -0.3]
 [-0.2 -0.3  3. ]]
[[ 1.4        -0.5         0.07071068]
 [-0.5         1.6        -0.35355339]
 [ 0.07071068 -0.35355339  3.        ]]
[[ 2.  -0.1  0.3]
 [-0.1  1.  -0.2]
 [ 0.3 -0.2  3. ]]
[[ 1.6         0.5         0.35355339]
 [ 0.5         1.4         0.07071068]
 [ 0.35355339  0.07071068  3.        ]]
[[ 1.   0.1  0.2]
 [ 0.1  2.   0.3]
 [ 0.2  0.3  3. ]]


In [102]:
# Check the rotation of stress vectors
stress = np.array([ 1000., -200., -200., 1., 2., 3.])
A = tm.compute_transformation_matrix(45.)

for i in range(8):
    stress = tm.rotate_stress(A, stress)
    print stress.reshape(-1)

[ 399.          401.         -200.          600.           -0.70710678
    3.53553391]
[ -2.00000000e+02   1.00000000e+03  -2.00000000e+02  -1.00000000e+00
  -3.00000000e+00   2.00000000e+00]
[ 401.          399.         -200.         -600.           -3.53553391
   -0.70710678]
[  1.00000000e+03  -2.00000000e+02  -2.00000000e+02   1.00000000e+00
  -2.00000000e+00  -3.00000000e+00]
[ 399.          401.         -200.          600.            0.70710678
   -3.53553391]
[ -2.00000000e+02   1.00000000e+03  -2.00000000e+02  -1.00000000e+00
   3.00000000e+00  -2.00000000e+00]
[ 401.          399.         -200.         -600.            3.53553391
    0.70710678]
[  1.00000000e+03  -2.00000000e+02  -2.00000000e+02   1.00000000e+00
   2.00000000e+00   3.00000000e+00]


In [103]:
# Check the rotation of stress matrices
stress = tm.convert_stress(np.array([ 1000., -200., -200., 1., 2., 3.]))
A = tm.compute_transformation_matrix(45.)

for i in range(8):
    stress = tm.rotate_stress(A, stress)
    print stress

[[ 399.          600.           -0.70710678]
 [ 600.          401.            3.53553391]
 [  -0.70710678    3.53553391 -200.        ]]
[[ -2.00000000e+02  -1.00000000e+00  -3.00000000e+00]
 [ -1.00000000e+00   1.00000000e+03   2.00000000e+00]
 [ -3.00000000e+00   2.00000000e+00  -2.00000000e+02]]
[[ 401.         -600.           -3.53553391]
 [-600.          399.           -0.70710678]
 [  -3.53553391   -0.70710678 -200.        ]]
[[  1.00000000e+03   1.00000000e+00  -2.00000000e+00]
 [  1.00000000e+00  -2.00000000e+02  -3.00000000e+00]
 [ -2.00000000e+00  -3.00000000e+00  -2.00000000e+02]]
[[ 399.          600.            0.70710678]
 [ 600.          401.           -3.53553391]
 [   0.70710678   -3.53553391 -200.        ]]
[[ -2.00000000e+02  -1.00000000e+00   3.00000000e+00]
 [ -1.00000000e+00   1.00000000e+03  -2.00000000e+00]
 [  3.00000000e+00  -2.00000000e+00  -2.00000000e+02]]
[[ 401.         -600.            3.53553391]
 [-600.          399.            0.70710678]
 [   3.535533

In [104]:
# Check the rotation of strain vectors
strain = np.array([ 1., 2., 3., 4., 5., 6.])
A = tm.compute_transformation_matrix(45.)

for i in range(8):
    strain = tm.rotate_strain(A, strain)
    print strain.reshape(-1)

[-0.5         3.5         3.         -1.         -0.70710678  7.77817459]
[ 2.  1.  3. -4. -6.  5.]
[ 3.5        -0.5         3.          1.         -7.77817459 -0.70710678]
[ 1.  2.  3.  4. -5. -6.]
[-0.5         3.5         3.         -1.          0.70710678 -7.77817459]
[ 2.  1.  3. -4.  6. -5.]
[ 3.5        -0.5         3.          1.          7.77817459  0.70710678]
[ 1.  2.  3.  4.  5.  6.]


In [105]:
# Check the rotation of strain matrices
strain = tm.convert_strain(np.array([ 1., 2., 3., 4., 5., 6.]))
A = tm.compute_transformation_matrix(45.)

for i in range(8):
    strain = tm.rotate_strain(A, strain)
    print strain

[[-0.5        -0.5        -0.35355339]
 [-0.5         3.5         3.8890873 ]
 [-0.35355339  3.8890873   3.        ]]
[[ 2.  -2.  -3. ]
 [-2.   1.   2.5]
 [-3.   2.5  3. ]]
[[ 3.5         0.5        -3.8890873 ]
 [ 0.5        -0.5        -0.35355339]
 [-3.8890873  -0.35355339  3.        ]]
[[ 1.   2.  -2.5]
 [ 2.   2.  -3. ]
 [-2.5 -3.   3. ]]
[[-0.5        -0.5         0.35355339]
 [-0.5         3.5        -3.8890873 ]
 [ 0.35355339 -3.8890873   3.        ]]
[[ 2.  -2.   3. ]
 [-2.   1.  -2.5]
 [ 3.  -2.5  3. ]]
[[ 3.5         0.5         3.8890873 ]
 [ 0.5        -0.5         0.35355339]
 [ 3.8890873   0.35355339  3.        ]]
[[ 1.   2.   2.5]
 [ 2.   2.   3. ]
 [ 2.5  3.   3. ]]


In [168]:
# Create an isotropic stiffness tensor and apply rotation
import laminate_analysis as la
mat = la.Material([72000., 0.23], symmetry_type='isotropic')
L = mat.stiffness_tensor
tm.print_n_by_n(L)

 8.347e+04 2.493e+04 2.493e+04 0.000e+00 0.000e+00 0.000e+00
 2.493e+04 8.347e+04 2.493e+04 0.000e+00 0.000e+00 0.000e+00
 2.493e+04 2.493e+04 8.347e+04 0.000e+00 0.000e+00 0.000e+00
 0.000e+00 0.000e+00 0.000e+00 2.927e+04 0.000e+00 0.000e+00
 0.000e+00 0.000e+00 0.000e+00 0.000e+00 2.927e+04 0.000e+00
 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 2.927e+04



In [169]:
Lrot = tm.rotate_stiffness(A, L)
np.testing.assert_array_almost_equal(L, Lrot)

In [170]:
Lrot = tm._rotate_fourth_order(A, L)
np.testing.assert_array_almost_equal(L, Lrot)

In [191]:
# create and rotate a transversely isotropic stiffness tensor

In [192]:
mat = la.Material([72000., 7000., 0.3, 0.23, 3000.], symmetry_type='transverse')
L = mat.stiffness_tensor
tm.print_n_by_n(L)

 7.367e+04 2.791e+03 2.791e+03 0.000e+00 0.000e+00 0.000e+00
 2.791e+03 7.497e+03 1.806e+03 0.000e+00 0.000e+00 0.000e+00
 2.791e+03 1.806e+03 7.497e+03 0.000e+00 0.000e+00 0.000e+00
 0.000e+00 0.000e+00 0.000e+00 3.000e+03 0.000e+00 0.000e+00
 0.000e+00 0.000e+00 0.000e+00 0.000e+00 3.000e+03 0.000e+00
 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 2.846e+03



In [193]:
Lrot = tm.rotate_stiffness(A, L)
for i in range(3):
    Lrot = tm.rotate_stiffness(A, Lrot)
tm.print_n_by_n(Lrot)

 7.367e+04 2.791e+03 2.791e+03-2.638e-11 0.000e+00 0.000e+00
 2.791e+03 7.497e+03 1.806e+03 3.638e-12 0.000e+00 0.000e+00
 2.791e+03 1.806e+03 7.497e+03 0.000e+00 0.000e+00 0.000e+00
-2.638e-11 3.638e-12 0.000e+00 3.000e+03 0.000e+00 0.000e+00
 0.000e+00 0.000e+00 0.000e+00 0.000e+00 3.000e+03-2.274e-13
 0.000e+00 0.000e+00 0.000e+00 0.000e+00-2.274e-13 2.846e+03



In [194]:
np.testing.assert_almost_equal(L, Lrot)

In [195]:
mat = la.Material([72000., 7000., 0.3, 0.23, 3000.], symmetry_type='transverse')
L = mat.stiffness_tensor
tm.print_n_by_n(L)
Lrot = tm._rotate_fourth_order(A, L)
for i in range(3):
    Lrot = tm._rotate_fourth_order(A, Lrot)
tm.print_n_by_n(Lrot)
np.testing.assert_almost_equal(L, Lrot)

 7.367e+04 2.791e+03 2.791e+03 0.000e+00 0.000e+00 0.000e+00
 2.791e+03 7.497e+03 1.806e+03 0.000e+00 0.000e+00 0.000e+00
 2.791e+03 1.806e+03 7.497e+03 0.000e+00 0.000e+00 0.000e+00
 0.000e+00 0.000e+00 0.000e+00 3.000e+03 0.000e+00 0.000e+00
 0.000e+00 0.000e+00 0.000e+00 0.000e+00 3.000e+03 0.000e+00
 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 2.846e+03

 7.367e+04 2.791e+03 2.791e+03-2.638e-11 0.000e+00 0.000e+00
 2.791e+03 7.497e+03 1.806e+03 3.638e-12 0.000e+00 0.000e+00
 2.791e+03 1.806e+03 7.497e+03 0.000e+00 0.000e+00 0.000e+00
-2.638e-11 3.638e-12 0.000e+00 3.000e+03 0.000e+00 0.000e+00
 0.000e+00 0.000e+00 0.000e+00 0.000e+00 3.000e+03-2.274e-13
 0.000e+00 0.000e+00 0.000e+00 0.000e+00-2.274e-13 2.846e+03



In [196]:
%timeit tm.rotate_stiffness(A, L)

100000 loops, best of 3: 17.6 µs per loop


In [197]:
%timeit tm._rotate_fourth_order(A, L)

10000 loops, best of 3: 28 µs per loop
